// The HCQHA membership terms, liability waiver and declaration, reproduced
// verbatim from the club's membership application form. Shown on the public
// "Become a member" page above the agreement checkbox. If the committee
// updates the wording, update the paragraphs below to match.

export const WAIVER_INTRO = [
  "I hereby apply for membership with the Hunter Coast Quarter Horse Association. I agree to be bound by its rules and regulations as set down in its constitution and as determined by the Committee from time to time. Membership fees are due 1st August each year.",
];

export const WAIVER_BODY = [
  "By submitting this form and paying the required fee, I/we agree to abide by the Constitution and the Rules and Regulations of AQHA and HCQHA furthermore, I/we declare that I/we have read, understood and agree to the terms and conditions of the Liability and waiver printed below. The purpose of this agreement is to limit the liability of the Provider to exclude liability for any personal injury or death to the Participant and other people in the care and control of the Participant howsoever caused who signed this form as acknowledgement of the terms and conditions of this agreement. By submitting this form, you are waiving your rights to sue the Provider for losses relating to personal injury or death. Under the provisions of the Trade Practices Act and Various State Laws conditions are implied into contracts that mean that the Provider of Recreational Services, noted below, is required to ensure that the Recreational Services it sells to you are: rendered with due care and skill, are fit for the purpose for which they are commonly bought as it is reasonable to expect in the circumstances or might reasonably be expected to achieve the result you have made known to the Provider.",
  "Name of Provider: Australian Quarter Horse Association, Lot 13 Jack Smyth Drive, TAMWORTH NSW 2340.",
  "The Participant acknowledges that the activity being undertaken is an activity being undertaken for the purposes of recreation, enjoyment or leisure which involves a significant degree of physical risk. The Provider acknowledges that they are providing Recreational Services detailed below which means; providing facilities for participation in a recreational activity or training a person to participate in a recreational activity, or supervising, adjudicating, guiding or otherwise assisting a person's participation in a recreational activity. The Participant hereby acknowledges that in attending the recreational activity that there are inherent risks involved to him or her or other people in their care and control. This agreement is directed and limited to inherent risks that are patent. The participants also acknowledges that the purpose of the recreational activity is for the benefit of the Participant and for the benefit of those people attending with the Participant and that at all times the Participant is responsible for his or her own actions and the actions of those other people in his or her care and control.",
  "Description of Recreational Services: HORSE RIDING & COMPETITION OF THE AUSTRALIAN QUARTER HORSE.",
  "Steps taken by the Australian Quarter Horse Association to avoid the danger of personal injury or death: 1. Providing assistance to Affiliates to support those Affiliates in the safe conduct of their activities. 2. Implementation of a risk management approach to events sanctioned by the Association. 3. Publication of resources to support the risk management approach of the Association and its Affiliates. 4. Implementation of the rules and regulations as agreed by the Board of Directors of the Association.",
  "The Participant acknowledges that during all times while he or she is attending the recreational activity, he or she does so at his or her own risk, and that the Participant, and other people in the care and control of the Participant, will not hold the Provider or any of its employees or agents liable for any personal injury or breach of contract whether caused by the negligence of the Provider its employees or agents howsoever caused or otherwise. The Participant acknowledges that in the event that he or she or any of the other people in their care and control find either or any of them is in difficulty that they are to stop the activity or request that the activity be stopped if appropriate, and seek help and/or assistance and advice.",
];

export const WAIVER_DECLARATION = [
  "Declaration: By submitting this agreement I/we understand that the Recreational Services, as set out in this form, may cause my/us and or my/our dependents personal injury or death. By submitting this agreement, I/we understand that I/we and my/our dependents waive our rights to sue the Provider for losses relating to my/our and or my/our dependents personal injury or death that result from any negligence caused by the Provider. I agree to abide by any additional rules that have been implemented by the AQHA regarding participation in affiliate and AQHA run events.",
];
